### ISSUE TITLE
Add a hotswap tutorial

### ISSUE THREAD

**Issue by SamHoque** [nea89o/Forge1.8.9Template#21]
hotswap for intelliJ? currently, I need to restart the game every time I make changes.

**Comment by romangraef** [comment]
Hotswap is not really part of the template, but rather your IDE Setup! If you want a tutorial on how to set it up, check out [NEUs Hot Reloading Tutorial](https://github.com/NotEnoughUpdates/NotEnoughUpdates/blob/master/CONTRIBUTING.md#hot-reloading). Keep in mind hotswapping will break some things, so you will still need to restart for some changes. I'm leaving this open as a reminder to add a hotswap tutorial into this template.

**Comment by nea89o** [comment]
https://moddev.nea.moe/hotswap/ exists now
