### ISSUE TITLE
How to shade a dependency?

### ISSUE THREAD

**Issue by DavidTheExplorer** [nea89o/Forge1.8.9Template#34]
I'm a Maven user who started modding a few days ago - Please forgive my basic gradle knowledge.
I'm trying to create an Hypixel mod, so I added the hypixel api:
![image](https://github.com/nea89o/Forge1.8.9Template/assets/69223217/c7b1f946-03cf-4a4e-88fc-c596012b8c1e)
![image](https://github.com/nea89o/Forge1.8.9Template/assets/69223217/2b452fb3-a979-4107-9c61-de7f028872a7)

The mod works within the IDE, but not when I create a jar.
I know from Maven that I need to shade and relocate the API, and I tried to do this:
![image](https://github.com/nea89o/Forge1.8.9Template/assets/69223217/8466e780-a859-4007-9577-70f8875aaa12)
But when I do `build` the jar file still doesn't contain the API...
What am I doing wrong?

**Comment by nea89o** [comment]
Instead of using `implementation` you need to use `shadowImpl`. This is done because in mods you want to be much more deliberate in what you include in your mod.

**Comment by DavidTheExplorer** [comment]
> Instead of using `implementation` you need to use `shadowImpl`. This is done because in mods you want to be much more deliberate in what you include in your mod.

It worked! :)
 But I have a question: Why did it relocate a transitive dependency outside of the `deps` package?
![image](https://github.com/nea89o/Forge1.8.9Template/assets/69223217/05554d51-7b33-4cdd-94e4-bf58a2d7fbe8)

**Comment by nea89o** [comment]
relocate works on package names. you will probably not want to shade gson at all, so you would want to exclude that dependency: 

```
shadowImpl("my:dependency:1.0.0") {
	exclude (group ="com.google.code.gson")
}
```

**Comment by DavidTheExplorer** [comment]
> relocate works on package names. you will probably not want to shade gson at all, so you would want to exclude that dependency:
> 
> ```
> shadowImpl("my:dependency:1.0.0") {
> 	exclude (group ="com.google.code.gson")
> }
> ```

Why would I not want to shade GSON if my dependency depends on it?
After you answer, you can close this because my problem is solved :)

**Comment by nea89o** [comment]
Normally you would want to shade the dependency as well (and also specify that package to relocate). However gson is already present in minecraft, so you can just use that versionn.
